spring:
  application:
    name: register-center-svc
server:
  port: 8082
eureka:
#  server:
#    responseCacheUpdateInvervalMs: 2000
#    enableSelfPreservation: false
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/