spring:
  application:
    name: bwic-svc
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8082/eureka